<a href="https://colab.research.google.com/github/25wh1a0517-beep/Nasscom/blob/main/numpy_Exercise_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Your code for Task 1 here:import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(0, 100)

# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10, 51, (5, 5))

# Display the arrays
print("\narr1_1:")
print(arr1_1)

print("\narr1_2:")
print(arr1_2)

print("\narr1_3:")
print(arr1_3)

print("\narr1_4:")
print(arr1_4)


print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
# Your code for Task 2 here:# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed).
val2_1 = data[2, 3]

# 2.2 Extract the first row.
row2_2 = data[0]

# 2.3 Extract the last column.
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, and columns 0 and 1.
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100 using boolean indexing.
filtered_elements2_5 = data[data > 100]

# Display the results
print("2.1 Element at row 2, column 3:")
print(val2_1)

print("\n2.2 First row:")
print(row2_2)

print("\n2.3 Last column:")
print(col2_3)

print("\n2.4 Sub-array (rows 1-2, columns 0-1):")
print(sub_arr2_4)

print("\n2.5 Elements greater than 100:")
print(filtered_elements2_5)


# Task 3: Conditional Operations
# Your code for Task 3 here:# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))  # Random 4x5 array with values 1 to 20

# Display the original array
print("Original Array (arr3_1):")
print(arr3_1)

# 3.1 Replace elements less than 10 with 0, keep others unchanged.
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count how many elements are even.
even_count3_3 = np.sum(arr3_1 % 2 == 0)

# Display the results
print("\nModified Array (arr3_2):")
print(arr3_2)

print("\nNumber of even elements:")
print(even_count3_3)



# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# Your code for Task 4 here:# Task 4: Aggregation Functions

# Display the original array
print("Original Array (arr4_1):")
print(arr4_1)

# 4.1 Calculate the sum of all elements.
sum4_1 = np.sum(arr4_1)

# 4.2 Calculate the mean of each column.
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3 Find the maximum value in each row.
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4 Calculate the standard deviation of the entire array.
std4_4 = np.std(arr4_1)

# Display the results
print("\n4.1 Sum of all elements:")
print(sum4_1)

print("\n4.2 Mean of each column:")
print(mean_cols4_2)

print("\n4.3 Maximum value in each row:")
print(max_rows4_3)

print("\n4.4 Standard deviation of the array:")
print(std4_4)



# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23

# Your code for Task 5 here:# Task 5: Reshaping and Flattening
# Display the original array
print("Original Array (arr5_1):")
print(arr5_1)

# 5.1 Reshape into a 4x6 2D array.
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into a 2x3x4 3D array.
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten the 2D array back into a 1D array.
flattened_arr5_4_ravel = reshaped_arr5_2.ravel()
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()

# Display the results
print("\n4x6 Reshaped Array (reshaped_arr5_2):")
print(reshaped_arr5_2)

print("\n2x3x4 Reshaped Array (reshaped_arr5_3):")
print(reshaped_arr5_3)

print("\nFlattened Array using ravel():")
print(flattened_arr5_4_ravel)

print("\nFlattened Array using flatten():")
print(flattened_arr5_4_flatten)



# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# Your code for Task 6 here:# Task 6: Broadcasting
# Display the original array
print("Original Array (arr6_1):")
print(arr6_1)

# 6.1 Add the scalar to every element.
result6_1 = arr6_1 + scalar

# 6.2 Add the vector to each row.
result6_2 = arr6_1 + vector

# Display the results
print("\nResult after adding scalar (10):")
print(result6_1)

print("\nResult after adding vector [100, 200, 300]:")
print(result6_2)



# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])

# Your code for Task 7 here:# Task 7: Copying vs. Viewing Arrays
# Display the original array
print("Original Array:")
print(original_arr7)

# 7.1 Create a view by slicing the entire array.
view_arr7 = original_arr7[:]

# Modify the first element of the view.
view_arr7[0] = 99

print("\nAfter modifying view_arr7:")
print("view_arr7:", view_arr7)
print("original_arr7:", original_arr7)  # Original array also changes

# 7.2 Create a copy of the original array.
copy_arr7 = original_arr7.copy()

# Modify the last element of the copy.
copy_arr7[-1] = 0

print("\nAfter modifying copy_arr7:")
print("copy_arr7:", copy_arr7)
print("original_arr7:", original_arr7)  # Original array remains unchanged



# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

# Your code for Task 8 here:# Task 8: Stacking and Splitting Arrays

# Display the original arrays
print("arr8_a:")
print(arr8_a)

print("\narr8_b:")
print(arr8_b)

print("\narr8_c:")
print(arr8_c)

# 8.1 Vertically stack arr8_a and arr8_b.
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2 Horizontally stack arr8_a and arr8_b.
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3 Vertically stack vstack_arr8_1 and arr8_c.
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4 Split combined_arr8_3 into 5 equal row parts (each part contains 1 row).
part1, part2, part3, part4, part5 = np.vsplit(combined_arr8_3, 5)

# Display the results
print("\n8.1 Vertical Stack:")
print(vstack_arr8_1)

print("\n8.2 Horizontal Stack:")
print(hstack_arr8_2)

print("\n8.3 Combined Array:")
print(combined_arr8_3)

print("\n8.4 Split Arrays:")
print("Part 1:")
print(part1)

print("Part 2:")
print(part2)

print("Part 3:")
print(part3)

print("Part 4:")
print(part4)

print("Part 5:")
print(part5)



# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# Your code for Task 9 here:# Task 9: Sorting and Searching
# Display the original arrays
print("Original 1D Array:")
print(arr9_1)

print("\nOriginal 2D Array:")
print(arr9_2d)

# 9.1 Sort arr9_1 in ascending order.
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort arr9_2d along columns (each column sorted independently).
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3 Find the indices where the value 9 is present.
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find the index of the maximum value.
max_idx9_4 = np.argmax(arr9_1)

# Display the results
print("\n9.1 Sorted 1D Array:")
print(sorted_arr9_1)

print("\n9.2 Columns Sorted Independently:")
print(sorted_cols9_2)

print("\n9.3 Index of value 9:")
print(idx9_3)

print("\n9.4 Index of the maximum value:")
print(max_idx9_4)






--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---

arr1_1:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

arr1_2:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

arr1_3:
[[7 7 7 7]
 [7 7 7 7]]

arr1_4:
[[22 30 45 27 39]
 [24 30 18 10 43]
 [34 21 49 46 31]
 [10 18 30 31 42]
 [28 33 28 19 24]]
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[22 30 45 27 39]
 [24 30 18 10 43]]

--- Task 2: Indexing and Slicing with Arrays ---
2.1 Element at row 2, column 3:
120

2.2 First row:
[10 20 30 40]

2.3 Last column:
[ 40  80 120 1