<a href="https://colab.research.google.com/github/25wh1a0517-beep/Nasscom/blob/main/Exercise_U3_python_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Given data
M = np.arange(1, 13).reshape(3, 4)   # shape (3, 4)
N = np.arange(1, 9).reshape(4, 2)    # shape (4, 2)
print('M:\n', M)
print('N:\n', N)

# 1. Matrix product M @ N
print('matrix multiplication:',M@N)
# 2. Column-wise sum (axis=0) and row-wise mean (axis=1) of M
print('column-wise sum:',np.sum(M,axis=0))
print('row-wise mean:',np.mean(M,axis=1))
# 3. Index of the max value in each row of M (hint: argmax with axis=1)
print('index of the max value in each row of M:',np.argmax(M,axis=1))

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
N:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
matrix multiplication: [[ 50  60]
 [114 140]
 [178 220]]
column-wise sum: [15 18 21 24]
row-wise mean: [ 2.5  6.5 10.5]
index of the max value in each row of M: [3 3 3]


In [ ]:
import seaborn as sns

lab = sns.load_dataset('titanic')   # fresh copy to work on

# 1. Count missing values in 'embarked'
print('count missing values in embarked:',lab['embarked'].isnull().sum())

# 2. Fill missing 'embarked' with the mode (hint: lab['embarked'].mode()[0])
print('fill missing embarked with the mode:',lab['embarked'].fillna(lab['embarked'].mode()[0]))

# 3. Mean fare grouped by 'sex'
print('mean fare grouped by sex:',lab.groupby('sex')['fare'].mean())

count missing values in embarked: 2
fill missing embarked with the mode: 0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: embarked, Length: 891, dtype: object
mean fare grouped by sex: sex
female    44.479818
male      25.523893
Name: fare, dtype: float64
